### ISSUE TITLE
Problem while setting up the project

### ISSUE THREAD

**Issue by kartikeys98** [internetarchive/internet-archive-google-action#160]
After running ```DEBUG=ia:* npm start``` I got this error message. Even after downgrading my node version to 6.11.5 with nvm it still remains. I have installed all dependencies. 

```
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
[2018-03-19T10:45:17.559Z] Error during trigger parsing:  Error occurred while parsing your function triggers.

TypeError: Cannot read property 'key' of undefined
    at Object.<anonymous> (/home/kartikey/ghub-repos/internet-archive-google-action/functions/index.js:12:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/kartikey/.nvm/versions/node/v6.11.5/lib/node_modules/firebase-tools/lib/triggerParser.js:18:11
    at Object.<anonymous> (/home/kartikey/.nvm/versions/node/v6.11.5/lib/node_modules/firebase-tools/lib/triggerParser.js:38:3)
⚠  functions: Error from emulator. Error occurred while parsing your function triggers.

TypeError: Cannot read property 'key' of undefined
    at Object.<anonymous> (/home/kartikey/ghub-repos/internet-archive-google-action/functions/index.js:12:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/kartikey/.nvm/versions/node/v6.11.5/lib/node_modules/firebase-tools/lib/triggerParser.js:18:11
    at Object.<anonymous> (/home/kartikey/.nvm/versions/node/v6.11.5/lib/node_modules/firebase-tools/lib/triggerParser.js:38:3)
```

**Comment by hyzhak** [comment]
it duplicates this one https://github.com/internetarchive/internet-archive-google-action/issues/159
