### ISSUE TITLE
Error during DynamoDB put:ValidationException: The parameter cannot be converted to a numeric value: NaN

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#225]
From time to time we are getting error

> Error during DynamoDB put:ValidationException: The parameter cannot be converted to a numeric value: NaN
Error saving state: ValidationException: The parameter cannot be converted to a numeric value: NaN
ValidationException: The parameter cannot be converted to a numeric value: NaN
    at Request.extractError (/functions/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/functions/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/functions/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/functions/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/functions/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/functions/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /functions/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/functions/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/functions/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/functions/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
INFO  2018-04-16T16:52:24.543Z ResponseReceived ID: 1523897539395
VERB  2018-04-16T16:52:24.543Z Payload:
Unhandled Exception from Lambda: ValidationException: The parameter cannot be converted to a numeric value: NaN
INFO  2

>  ia:platform:alexa:error-handler:error Caught Error: { AskSdk.DynamoDbPersistenceAdapter Error: Could not save item (amzn1.ask.account.AESW4Y2T3NOFH6AFOZRROM46HVP7RXZWITXM4HFDY2G72UTHWQOJRWBPH26T7NHIGKF7NHYZQVAQUXCZSMHH3NL7L5CSBAFWGCZRBMDCYI5U5MB7BP2UCUWYOPD2IDAVLVOMLLFRF6LE4UPFBSNV43JLCMMS2DP3NFS7CRDH2SC5DFJETU6KSANDZ2G6CCHXEXE4CGF2CFQFHRA) to table (InternetArchiveSessions): The parameter cannot be converted to a numeric value: NaN
    at Object.createAskSdkError (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/utils/AskSdkUtils.js:22:17)
    at DynamoDbPersistenceAdapter.<anonymous> (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/attributes/persistence/DynamoDbPersistenceAdapter.js:168:45)
    at step (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/attributes/persistence/DynamoDbPersistenceAdapter.js:44:23)
    at Object.throw (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/attributes/persistence/DynamoDbPersistenceAdapter.js:25:53)
    at rejected (./functions/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/attributes/persistence/DynamoDbPersistenceAdapter.js:17:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) name: 'AskSdk.DynamoDbPersistenceAdapter Error' }

Steps to reproduce:
> [User] open internet archive
> [User] 78s collection
> [User] dance

**Comment by hyzhak** [comment]
related issue https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/378
