### ISSUE TITLE
Can't play random grateful dead

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#383]
steps to reproduce:
> live
> grateful dead
> randomly

we are getting error:

>   ia:actions:middlewares:playlist-from-feeder:[warning] fail on creating playlist. Got Error: TypeError: Cannot read property 'collection' of undefined
>     at axios.get.catch.then.res (.../functions/src/provider/albums.js:42:12)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by hyzhak** [comment]
we are trying to get album metadata from https://askills-api.archive.org/metadata/gd1988-09-08.141741.ots.akg.ackerman.miller.noel.t-flac2496

but should
https://askills-api.archive.org/metadata/gd1985-03-31.141602.OTS.AT835b-AKGD12e-Blend.Ackerman.Miller.Noel.t-flac2496
