### ISSUE TITLE
Error while running local server

### ISSUE THREAD

**Issue by yagyanshbhatia** [internetarchive/internet-archive-google-action#434]
I've set up the intents and entities, but I'm having trouble hosting a local server
@hyzhak Please look into the issue :smile: 
```
TypeError: Cannot read property 'key' of undefined
    at module.exports (/home/yagyansh/internet-archive-google-action/functions/src/platform/assistant/handler.js:27:60)
    at Object.<anonymous> (/home/yagyansh/internet-archive-google-action/functions/index.js:27:21)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:15:15
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:53:3)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
I get the same issue if I try to host it locally by `npm start` or `firebase serve`

**Comment by hyzhak** [comment]
ok, I've got it, in this line we read config from `firebase` and missed it. So you should have fake config there, for example like this one https://github.com/internetarchive/internet-archive-google-action/blob/master/functions/tests/.runtimeconfig.json. Actually it is long running issue. Those config props should optional, but we should warn developer there that they may missed some important config params

**Comment by hyzhak** [comment]
this issue seems similar to that one https://github.com/internetarchive/internet-archive-google-action/issues/145

**Comment by yagyanshbhatia** [comment]
Actually I can't host it due to this, hence my ngrok link doesn't work. I can't start development till then. Are you working on this issue? Or is there a temporary workaround I can use to bypass this and start hacking on the project?
I tried a lot of things, but couldn't get through it.

**Comment by Dharmesh-Poddar** [comment]
@hyzhak I'm also stuck in setting this project locally.I have already mailed you all pictures of the steps that I followed and the error I'm getting while setting it locally.

**Comment by hyzhak** [comment]
@yagyanshbhatia could describe in details the issue with `ngrok`, so I could replicate it locally?

**Comment by hyzhak** [comment]
@Dharmesh-Poddar According to your screen shots, your issue isn't related to the @yagyanshbhatia issue. You don't need to deploy action to try it locally, you can run it on your desktop by `npm start` btw, I'd recommend to read carefully tutorial and create at least on action of google in node.js. It would solve a lot issues which you could face in that way

**Comment by yagyanshbhatia** [comment]
@hyzhak can you tell me where do I need to add the `fake config` you are talking about?? to bypass this error. 
`ngrok` is not producing the error, its the `firebase deploy` that gives this error.

**Comment by yagyanshbhatia** [comment]
@hyzhak  Please accept the slack invite I sent you, I'll be really grateful :smile: 
I've sent the invite on `ievgenii.krevenets@gmail.com`
